store: "fuseki"
username: "imitrob"
password: "kognitron"
port: "4242"
fuseki_path: "apache-jena-fuseki" # ie $CROW_LIB_DIR/apache-jena-fuseki
host: 127.0.0.1 # 192.168.88.146
database: "onto"
baseURL: "http://imitrob.ciirc.cvut.cz/ontologies/crow"
