languages: ["CZ", "EN"]
tab:
  detection:
    - "detekce"
    - "detections"
  cmd_queue:
    - "příkazová fronta"
    - "command queue"
  camera:
    - "kamery"
    - "cameras"
  parameter:
    - "parametry"
    - "parameters"
  object:
    - "objekty"
    - "objects"
input:
  select_camera:
    - "vyberte kameru"
    - "select camera"
  nlp_suspend:
    - "Pozastavit NLP"
    - "Suspend NLP"
  cmd_cancel:
    - "Zrušit příkaz"
    - "Cancel command"
field:
  nlp_suspended:
    - "NLP pozastaveno"
    - "NLP suspended"
  nlp_mode:
    - "Režim NLP"
    - "NLP mode"
  silent_mode:
    - "Tichý režim"
    - "Silent mode"
  detected_cmd:
    - "Detekovany prikaz"
    - "Detected command"
  detected_object:
    - "Detekovany objekt"
    - "Detected object"
  detected_name:
    - "Detekovany objekt (jmeno)"
    - "Detected object (name)"
  detected_is_present:
    - "Objekt je na pracovisti?"
    - "Object in workspace?"
  state:
    - "Stav"
    - "State"
  cmd_queue:
    - "Příkazy v pořadí"
    - "Command queue"
  object:
    - "objekt"
    - "object"
  location:
    - "lokace"
    - "location"
  id:
    - "id"
    - "id"
  command:
    - "příkaz"
    - "command"
  command_name:
    - "jméno příkazu"
    - "command name"
  info:
    - "info"
    - "info"
  target:
    - "cíl"
    - "target"
option:
  yes:
    - "ano"
    - "yes"
  no:
    - "ne"
    - "no"
  "True":
    - "ano"
    - "yes"
  "False":
    - "ne"
    - "no"
  "None":
    - "N/A"
    - "N/A"
nlp_mode:
  "None":
    - "-"
    - "N/A"
  "1":
    - "Tichý"
    - "Silent"
  "2":
    - "Mluvení"
    - "Speaking"
  "3":
    - "Plné mluvení"
    - "Full speach"
action:
  point:
    - "ukaž"
    - "point"
  pick:
   - "seber"
   - "pick"
  fetch:
   - "podej"
   - "fetch"
button:
  command_rm:
    - "Odstraň příkaz"
    - "Remove command"
info:
  infoText:
    - "Prikazy\nUkaz na <OBJEKT>\nUkaz na <BARVA> <OBJEKT>\nSeber <OBJEKT>"
    - "Commands\nPoint at <OBJECT>\nPoint at <COLOR> <OBJECT>\nPick up <OBJECT>"